import { Plus, Trash2, Sparkles, Loader2, X, Check, Wand2, Lightbulb } from 'lucide-react';
import { Experience } from '../types';
import { generateAIContent, rewriteForJob } from '../lib/gemini';
import { useState } from 'react';

interface ExperienceFormProps {
  data: Experience[];
  onChange: (data: Experience[]) => void;
  targetJD?: string;
}

export default function ExperienceForm({ data, onChange, targetJD }: ExperienceFormProps) {
  const [generatingFor, setGeneratingFor] = useState<string | null>(null);
  const [improvingFor, setImprovingFor] = useState<string | null>(null);
  const [previewData, setPreviewData] = useState<{
    id: string;
    original: string;
    improved: string;
    type: 'generate' | 'improve';
  } | null>(null);

  const addExperience = () => {
    const newExp: Experience = {
      id: Date.now().toString(),
      company: '',
      position: '',
      location: '',
      startDate: '',
      endDate: '',
      current: false,
      description: '',
    };
    onChange([...data, newExp]);
  };

  const updateExperience = (id: string, field: keyof Experience, value: string | boolean) => {
    onChange(data.map(exp => exp.id === id ? { ...exp, [field]: value } : exp));
  };

  const removeExperience = (id: string) => {
    onChange(data.filter(exp => exp.id !== id));
  };

  const autoGenerateDescription = async (id: string, position: string, company: string, currentDescription: string) => {
    if (!position) {
      alert('Please enter a position first');
      return;
    }

    setGeneratingFor(id);
    try {
      const prompt = targetJD
        ? `Generate 4-5 high-impact bullet points for a ${position} role at ${company || 'a company'}, specifically tailored to this Job Description:
        ${targetJD.slice(0, 2000)}
        Focus on achievements and action verbs. Return the bullet points separated by newlines, each starting with '•'. NO BOLDING or markdown.`
        : `Generate 4-5 high-impact bullet points for a ${position} role at ${company || 'a company'}. 
        Use action verbs and focus on achievements. 
        Return the bullet points separated by newlines, each starting with '•'. NO BOLDING or markdown.`;

      const result = await generateAIContent(prompt);

      if (!currentDescription.trim()) {
        updateExperience(id, 'description', result.content);
      } else {
        setPreviewData({
          id,
          original: currentDescription,
          improved: result.content,
          type: 'generate'
        });
      }
    } catch (error) {
      console.error('AI description generation error:', error);
    } finally {
      setGeneratingFor(null);
    }
  };

  const handleImproveDescription = async (id: string, description: string) => {
    if (!description.trim()) return;
    setImprovingFor(id);
    try {
      const improved = await rewriteForJob(description, targetJD || '', "Work Experience");
      setPreviewData({
        id,
        original: description,
        improved,
        type: 'improve'
      });
    } catch (error) {
      console.error('AI improvement error:', error);
    } finally {
      setImprovingFor(null);
    }
  };

  const applyPreview = () => {
    if (previewData) {
      updateExperience(previewData.id, 'description', previewData.improved);
      setPreviewData(null);
    }
  };

  return (
    <div className="space-y-6 relative">
      <div className="flex justify-between items-center">
        <div className="flex items-center gap-3">
          <div className="bg-gradient-to-br from-emerald-500 to-teal-500 text-white rounded-xl p-2 shadow-lg">
            <Sparkles size={24} />
          </div>
          <h3 className="text-2xl font-bold bg-gradient-to-r from-emerald-600 to-teal-600 bg-clip-text text-transparent">Work Experience</h3>
        </div>
        <button
          onClick={addExperience}
          className="flex items-center gap-2 px-5 py-2.5 bg-gradient-to-r from-emerald-500 to-teal-500 text-white rounded-xl hover:from-emerald-600 hover:to-teal-600 transition-all text-sm font-semibold shadow-lg hover:shadow-xl hover:scale-105 transform"
        >
          <Plus size={18} />
          Add Experience
        </button>
      </div>

      <div className="space-y-6">
        {data.map((exp, index) => (
          <div key={exp.id} className="p-6 border-2 border-emerald-200 rounded-2xl bg-gradient-to-br from-emerald-50 to-teal-50 space-y-4 shadow-lg hover:shadow-xl transition-all">
            <div className="flex justify-between items-start">
              <span className="text-base font-bold text-emerald-700 bg-white px-4 py-1.5 rounded-full shadow-sm">Experience #{index + 1}</span>
              <button
                type="button"
                onClick={() => removeExperience(exp.id)}
                className="text-red-600 hover:text-red-700 bg-white p-2 rounded-xl hover:bg-red-50 transition-all shadow-sm"
              >
                <Trash2 size={20} />
              </button>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-bold text-gray-800 mb-2">
                  Company *
                </label>
                <input
                  type="text"
                  value={exp.company}
                  onChange={(e) => updateExperience(exp.id, 'company', e.target.value)}
                  className="w-full px-4 py-3 border-2 border-emerald-200 rounded-xl focus:ring-4 focus:ring-emerald-300 focus:border-emerald-500 transition-all font-medium bg-white shadow-sm hover:shadow-md"
                  placeholder="Acme Corp"
                />
              </div>

              <div>
                <label className="block text-sm font-bold text-gray-800 mb-2">
                  Position *
                </label>
                <input
                  type="text"
                  value={exp.position}
                  onChange={(e) => updateExperience(exp.id, 'position', e.target.value)}
                  className="w-full px-4 py-3 border-2 border-teal-200 rounded-xl focus:ring-4 focus:ring-teal-300 focus:border-teal-500 transition-all font-medium bg-white shadow-sm hover:shadow-md"
                  placeholder="Software Engineer"
                />
              </div>

              <div className="md:col-span-2">
                <label className="block text-sm font-bold text-gray-800 mb-2">
                  Location
                </label>
                <input
                  type="text"
                  value={exp.location}
                  onChange={(e) => updateExperience(exp.id, 'location', e.target.value)}
                  className="w-full px-4 py-3 border-2 border-cyan-200 rounded-xl focus:ring-4 focus:ring-cyan-300 focus:border-cyan-500 transition-all font-medium bg-white shadow-sm hover:shadow-md"
                  placeholder="San Francisco, CA"
                />
              </div>
            </div>

            <div className="flex gap-3">
              <div className="flex-1">
                <label className="block text-sm font-bold text-gray-800 mb-2">
                  Start Date *
                </label>
                <input
                  type="month"
                  value={exp.startDate}
                  onChange={(e) => updateExperience(exp.id, 'startDate', e.target.value)}
                  className="w-full px-4 py-3 border-2 border-blue-200 rounded-xl focus:ring-4 focus:ring-blue-300 focus:border-blue-500 transition-all font-medium bg-white shadow-sm hover:shadow-md"
                />
              </div>

              <div className="flex-1">
                <label className="block text-sm font-bold text-gray-800 mb-2">
                  End Date
                </label>
                <input
                  type="month"
                  value={exp.endDate}
                  onChange={(e) => updateExperience(exp.id, 'endDate', e.target.value)}
                  disabled={exp.current}
                  className="w-full px-4 py-3 border-2 border-purple-200 rounded-xl focus:ring-4 focus:ring-purple-300 focus:border-purple-500 transition-all font-medium bg-white shadow-sm hover:shadow-md disabled:bg-gray-100"
                />
              </div>
            </div>

            <div className="flex items-center">
              <input
                type="checkbox"
                checked={exp.current}
                onChange={(e) => updateExperience(exp.id, 'current', e.target.checked)}
                className="w-4 h-4 text-blue-600 rounded focus:ring-blue-500"
              />
              <label className="ml-2 text-sm text-gray-700">
                I currently work here
              </label>
            </div>

            <div>
              <div className="flex justify-between items-center mb-2">
                <label className="block text-sm font-medium text-gray-700">
                  Description
                </label>
                <div className="flex gap-2">
                  <button
                    type="button"
                    onClick={() => autoGenerateDescription(exp.id, exp.position, exp.company, exp.description)}
                    disabled={generatingFor === exp.id || !exp.position}
                    className="flex items-center gap-1.5 px-3 py-1 bg-gradient-to-r from-blue-600 to-indigo-600 text-white rounded-lg hover:from-blue-700 hover:to-indigo-700 transition-all text-xs font-medium disabled:opacity-50 disabled:cursor-not-allowed shadow-sm"
                  >
                    {generatingFor === exp.id ? (
                      <>
                        <Loader2 size={14} className="animate-spin" />
                        Generating...
                      </>
                    ) : (
                      <>
                        <Sparkles size={14} />
                        AI Generate
                      </>
                    )}
                  </button>
                  {exp.description && (
                    <button
                      type="button"
                      onClick={() => handleImproveDescription(exp.id, exp.description)}
                      disabled={improvingFor === exp.id || generatingFor === exp.id}
                      className="flex items-center gap-1.5 px-3 py-1 bg-gradient-to-r from-purple-600 to-pink-600 text-white rounded-lg hover:from-purple-700 hover:to-pink-700 transition-all text-xs font-medium disabled:opacity-50 disabled:cursor-not-allowed shadow-sm"
                    >
                      {improvingFor === exp.id ? (
                        <>
                          <Loader2 size={14} className="animate-spin" />
                          Improving...
                        </>
                      ) : (
                        <>
                          <Sparkles size={14} />
                          AI Improve {targetJD ? '(Targeted)' : ''}
                        </>
                      )}
                    </button>
                  )}
                </div>
              </div>
              <textarea
                value={exp.description}
                onChange={(e) => updateExperience(exp.id, 'description', e.target.value)}
                rows={6}
                className="w-full px-3 py-2.5 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 transition-all text-sm"
                placeholder="Describe your responsibilities and achievements... or use AI Generate"
              />
              <p className="text-xs text-gray-500 mt-1">
                Tip: Enter your position title and click "AI Generate" for smart suggestions based on your role
              </p>
            </div>
          </div>
        ))}

        {data.length === 0 && (
          <div className="text-center py-8 text-gray-500">
            No work experience added yet. Click "Add Experience" to get started.
          </div>
        )}
      </div>

      {/* Preview Modal */}
      {previewData && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/50 backdrop-blur-sm animate-fade-in">
          <div className="bg-white rounded-2xl shadow-2xl max-w-4xl w-full flex flex-col max-h-[90vh]">
            <div className="p-6 border-b border-gray-100 flex items-center justify-between">
              <div className="flex items-center gap-2">
                <Sparkles className="text-emerald-600" size={20} />
                <h3 className="text-xl font-bold text-gray-900">Review AI Content</h3>
              </div>
              <button
                onClick={() => setPreviewData(null)}
                className="p-2 hover:bg-gray-100 rounded-full text-gray-400 hover:text-gray-600 transition-colors"
              >
                <X size={20} />
              </button>
            </div>

            <div className="p-6 overflow-y-auto custom-scrollbar flex-1">
              <div className="mb-6 bg-emerald-50 p-4 rounded-xl border border-emerald-100">
                <div className="flex items-start gap-2">
                  <Lightbulb className="text-emerald-600 mt-0.5" size={18} />
                  <div>
                    <p className="text-sm font-bold text-emerald-900 mb-1">
                      {previewData.type === 'generate' ? 'AI Generated Content' : 'AI Improved Content'}
                    </p>
                    <p className="text-xs text-emerald-800 font-medium">
                      Review the changes below. You can apply them or cancel to keep your original text.
                    </p>
                  </div>
                </div>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div className="space-y-2">
                  <span className="text-xs font-bold text-gray-500 uppercase tracking-widest pl-1">Original</span>
                  <div className="p-4 rounded-xl bg-gray-50 border border-gray-200 text-sm leading-relaxed text-gray-600 whitespace-pre-wrap h-full min-h-[200px]">
                    {previewData.original}
                  </div>
                </div>
                <div className="space-y-2">
                  <span className="text-xs font-bold text-emerald-600 uppercase tracking-widest pl-1">Improved Version</span>
                  <div className="p-4 rounded-xl bg-emerald-50 border border-emerald-100 text-sm leading-relaxed text-emerald-900 whitespace-pre-wrap h-full min-h-[200px] relative">
                    <div className="absolute top-2 right-2">
                      <Wand2 size={12} className="text-emerald-400" />
                    </div>
                    {previewData.improved}
                  </div>
                </div>
              </div>
            </div>

            <div className="p-6 border-t border-gray-100 bg-gray-50 rounded-b-2xl flex justify-end gap-3">
              <button
                onClick={() => setPreviewData(null)}
                className="px-5 py-2.5 rounded-xl font-bold text-gray-600 hover:bg-gray-200 hover:text-gray-800 transition-colors"
              >
                Cancel
              </button>
              <button
                onClick={applyPreview}
                className="px-6 py-2.5 bg-emerald-600 text-white rounded-xl font-bold shadow-lg hover:bg-emerald-700 hover:shadow-xl hover:-translate-y-0.5 transition-all flex items-center gap-2"
              >
                <Check size={18} />
                Apply Changes
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
