import React, { useState } from 'react';
import { Plus, Trash2, GripVertical, ChevronDown, ChevronUp, Sparkles, Loader2 } from 'lucide-react';
import { generateAIContent, rewriteForJob } from '../lib/gemini';

interface Project {
    id: string;
    name: string;
    description: string;
    technologies: string[];
    url: string;
    startDate: string;
    endDate: string;
}

interface ProjectsFormProps {
    data: Project[];
    onChange: (data: Project[]) => void;
    targetJD?: string;
}

const ProjectsForm: React.FC<ProjectsFormProps> = ({ data, onChange, targetJD }) => {
    const [expandedIds, setExpandedIds] = useState<string[]>([]);
    const [improvingFor, setImprovingFor] = useState<string | null>(null);
    const [isGenerating, setIsGenerating] = useState<string | null>(null);

    const toggleExpand = (id: string) => {
        setExpandedIds(prev =>
            prev.includes(id) ? prev.filter(i => i !== id) : [...prev, id]
        );
    };

    const handleChange = (id: string, field: keyof Project, value: any) => {
        const newData = data.map(item => {
            if (item.id === id) {
                return { ...item, [field]: value };
            }
            return item;
        });
        onChange(newData);
    };

    const handleTechnologyChange = (id: string, value: string) => {
        const techs = value.split(',').map(t => t.trim()).filter(Boolean);
        handleChange(id, 'technologies', techs);
    };

    const addProject = () => {
        const newProject: Project = {
            id: Date.now().toString(),
            name: '',
            description: '',
            technologies: [],
            url: '',
            startDate: '',
            endDate: ''
        };
        onChange([...data, newProject]);
        setExpandedIds(prev => [...prev, newProject.id]);
    };

    const removeProject = (id: string) => {
        if (confirm('Are you sure you want to remove this project?')) {
            onChange(data.filter(item => item.id !== id));
        }
    };

    const handleImproveDescription = async (id: string, description: string) => {
        if (!description.trim()) return;
        setImprovingFor(id);
        try {
            const improved = await rewriteForJob(description, targetJD || '', "Project Description");
            handleChange(id, 'description', improved);
        } catch (error) {
            console.error('AI improvement error:', error);
        } finally {
            setImprovingFor(null);
        }
    };

    const autoGenerateDescription = async (id: string, name: string) => {
        if (!name) return;
        setIsGenerating(id);
        try {
            const prompt = targetJD
                ? `Generate 3-4 professional bullet points for a project named "${name}", specifically tailored to this Job Description:
                ${targetJD.slice(0, 2000)}
                Focus on technical implementation and outcomes. Return the bullet points separated by newlines, each starting with '•'. NO BOLDING or markdown.`
                : `Generate 3-4 professional bullet points for a project named "${name}". 
                Include technical details and outcomes. 
                Return the bullet points separated by newlines, each starting with '•'. NO BOLDING or markdown.`;

            const result = await generateAIContent(prompt);
            handleChange(id, 'description', result.content);
        } catch (error) {
            console.error('AI project generation error:', error);
        } finally {
            setIsGenerating(null);
        }
    };

    const moveProject = (index: number, direction: 'up' | 'down') => {
        if (
            (direction === 'up' && index === 0) ||
            (direction === 'down' && index === data.length - 1)
        ) {
            return;
        }

        const newData = [...data];
        const newIndex = direction === 'up' ? index - 1 : index + 1;
        [newData[index], newData[newIndex]] = [newData[newIndex], newData[index]];
        onChange(newData);
    };

    return (
        <div className="space-y-6">
            <div className="flex justify-between items-center mb-4">
                <h3 className="text-lg font-semibold text-gray-800">Projects</h3>
                <button
                    onClick={addProject}
                    className="flex items-center gap-2 bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 transition-colors text-sm font-medium"
                >
                    <Plus size={16} /> Add Project
                </button>
            </div>

            {data.length === 0 ? (
                <div className="text-center py-8 bg-gray-50 border-2 border-dashed border-gray-200 rounded-xl">
                    <p className="text-gray-500 mb-2">No projects added yet.</p>
                    <button
                        onClick={addProject}
                        className="text-blue-600 hover:text-blue-700 font-medium text-sm"
                    >
                        Add your first project
                    </button>
                </div>
            ) : (
                <div className="space-y-4">
                    {data.map((project, index) => (
                        <div
                            key={project.id}
                            className="bg-white border border-gray-200 rounded-xl overflow-hidden shadow-sm transition-all hover:shadow-md"
                        >
                            <div
                                className="flex items-center justify-between p-4 bg-gray-50 cursor-pointer select-none"
                                onClick={() => toggleExpand(project.id)}
                            >
                                <div className="flex items-center gap-3">
                                    <div className="text-gray-400 cursor-move hover:text-gray-600 p-1">
                                        <GripVertical size={16} />
                                    </div>
                                    <span className="font-semibold text-gray-700">
                                        {project.name || '(Untitled Project)'}
                                    </span>
                                </div>
                                <div className="flex items-center gap-2">
                                    <button
                                        onClick={(e) => { e.stopPropagation(); moveProject(index, 'up'); }}
                                        disabled={index === 0}
                                        className="p-1 text-gray-400 hover:text-gray-600 disabled:opacity-30"
                                    >
                                        <ChevronUp size={16} />
                                    </button>
                                    <button
                                        onClick={(e) => { e.stopPropagation(); moveProject(index, 'down'); }}
                                        disabled={index === data.length - 1}
                                        className="p-1 text-gray-400 hover:text-gray-600 disabled:opacity-30"
                                    >
                                        <ChevronDown size={16} />
                                    </button>
                                    <button
                                        onClick={(e) => { e.stopPropagation(); removeProject(project.id); }}
                                        className="p-1 text-red-400 hover:text-red-600 ml-2"
                                    >
                                        <Trash2 size={16} />
                                    </button>
                                    <div className="ml-2 text-gray-400">
                                        {expandedIds.includes(project.id) ? <ChevronUp size={18} /> : <ChevronDown size={18} />}
                                    </div>
                                </div>
                            </div>

                            {expandedIds.includes(project.id) && (
                                <div className="p-5 space-y-4 animate-fade-in-down">
                                    <div>
                                        <label className="block text-xs font-semibold text-gray-600 uppercase tracking-wider mb-1">
                                            Project Name
                                        </label>
                                        <input
                                            type="text"
                                            value={project.name}
                                            onChange={(e) => handleChange(project.id, 'name', e.target.value)}
                                            className="w-full p-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 outline-none transition-all"
                                            placeholder="e.g. E-Commerce Platform"
                                        />
                                    </div>

                                    <div>
                                        <div className="flex justify-between items-center mb-1">
                                            <label className="block text-xs font-semibold text-gray-600 uppercase tracking-wider">
                                                Description
                                            </label>
                                            <div className="flex gap-2">
                                                <button
                                                    onClick={() => autoGenerateDescription(project.id, project.name)}
                                                    disabled={!!isGenerating || !!improvingFor}
                                                    className="flex items-center gap-1.5 px-2 py-1 bg-blue-100 text-blue-700 rounded-md hover:bg-blue-200 transition-all text-[10px] font-bold disabled:opacity-50"
                                                >
                                                    {isGenerating === project.id ? <Loader2 size={12} className="animate-spin" /> : <Sparkles size={12} />}
                                                    AI Generate
                                                </button>
                                                {project.description && (
                                                    <button
                                                        onClick={() => handleImproveDescription(project.id, project.description)}
                                                        disabled={!!improvingFor || !!isGenerating}
                                                        className="flex items-center gap-1.5 px-2 py-1 bg-purple-100 text-purple-700 rounded-md hover:bg-purple-200 transition-all text-[10px] font-bold disabled:opacity-50"
                                                    >
                                                        {improvingFor === project.id ? <Loader2 size={12} className="animate-spin" /> : <Sparkles size={12} />}
                                                        AI Improve {targetJD ? '(Targeted)' : ''}
                                                    </button>
                                                )}
                                            </div>
                                        </div>
                                        <textarea
                                            value={project.description}
                                            onChange={(e) => handleChange(project.id, 'description', e.target.value)}
                                            rows={4}
                                            className="w-full p-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 outline-none transition-all resize-y"
                                            placeholder="Describe the project, your role, and key achievements..."
                                        />
                                    </div>

                                    <div>
                                        <label className="block text-xs font-semibold text-gray-600 uppercase tracking-wider mb-1">
                                            Technologies (Comma Separated)
                                        </label>
                                        <input
                                            type="text"
                                            value={project.technologies.join(', ')}
                                            onChange={(e) => handleTechnologyChange(project.id, e.target.value)}
                                            className="w-full p-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 outline-none transition-all"
                                            placeholder="e.g. React, Node.js, MongoDB"
                                        />
                                    </div>

                                    <div className="grid grid-cols-2 gap-4">
                                        <div>
                                            <label className="block text-xs font-semibold text-gray-600 uppercase tracking-wider mb-1">
                                                Project URL
                                            </label>
                                            <input
                                                type="url"
                                                value={project.url || ''}
                                                onChange={(e) => handleChange(project.id, 'url', e.target.value)}
                                                className="w-full p-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 outline-none transition-all"
                                                placeholder="https://..."
                                            />
                                        </div>
                                        <div className="grid grid-cols-2 gap-2">
                                            <div>
                                                <label className="block text-xs font-semibold text-gray-600 uppercase tracking-wider mb-1">
                                                    Start Date
                                                </label>
                                                <input
                                                    type="text"
                                                    value={project.startDate || ''}
                                                    onChange={(e) => handleChange(project.id, 'startDate', e.target.value)}
                                                    className="w-full p-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 outline-none transition-all"
                                                    placeholder="MM/YYYY"
                                                />
                                            </div>
                                            <div>
                                                <label className="block text-xs font-semibold text-gray-600 uppercase tracking-wider mb-1">
                                                    End Date
                                                </label>
                                                <input
                                                    type="text"
                                                    value={project.endDate || ''}
                                                    onChange={(e) => handleChange(project.id, 'endDate', e.target.value)}
                                                    className="w-full p-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 outline-none transition-all"
                                                    placeholder="MM/YYYY"
                                                />
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            )}
                        </div>
                    ))}
                </div>
            )}
        </div>
    );
};

export default ProjectsForm;
