import { Plus, Trash2, Sparkles, Loader2 } from 'lucide-react';
import { Experience } from '../types';
import { generateAIContent, rewriteForJob } from '../lib/gemini';
import { useState } from 'react';

interface InternshipsFormProps {
    data: Experience[];
    onChange: (data: Experience[]) => void;
    targetJD?: string;
}

export default function InternshipsForm({ data, onChange, targetJD }: InternshipsFormProps) {
    const [generatingFor, setGeneratingFor] = useState<string | null>(null);

    const addInternship = () => {
        const newExp: Experience = {
            id: Date.now().toString(),
            company: '',
            position: '',
            location: '',
            startDate: '',
            endDate: '',
            current: false,
            description: '',
        };
        onChange([...data, newExp]);
    };

    const updateInternship = (id: string, field: keyof Experience, value: string | boolean) => {
        onChange(data.map(exp => exp.id === id ? { ...exp, [field]: value } : exp));
    };

    const removeInternship = (id: string) => {
        onChange(data.filter(exp => exp.id !== id));
    };

    const [improvingFor, setImprovingFor] = useState<string | null>(null);

    const autoGenerateDescription = async (id: string, position: string, company: string) => {
        if (!position) {
            alert('Please enter a position first');
            return;
        }

        setGeneratingFor(id);
        try {
            const prompt = targetJD
                ? `Generate 4-5 high-impact bullet points for a ${position} internship at ${company || 'a company'}, specifically tailored to this Job Description:
                ${targetJD.slice(0, 2000)}
                Focus on learning, achievements and action verbs. Return the bullet points separated by newlines, each starting with '•'. NO BOLDING or markdown.`
                : `Generate 4-5 high-impact bullet points for a ${position} internship at ${company || 'a company'}. 
                Use action verbs and focus on learning and achievements. 
                Return the bullet points separated by newlines, each starting with '•'. NO BOLDING or markdown.`;

            const result = await generateAIContent(prompt);
            updateInternship(id, 'description', result.content);
        } catch (error) {
            console.error('AI description generation error:', error);
        } finally {
            setGeneratingFor(null);
        }
    };

    const handleImproveDescription = async (id: string, description: string) => {
        if (!description.trim()) return;
        setImprovingFor(id);
        try {
            const improved = await rewriteForJob(description, targetJD || '', "Internship Experience");
            updateInternship(id, 'description', improved);
        } catch (error) {
            console.error('AI improvement error:', error);
        } finally {
            setImprovingFor(null);
        }
    };

    return (
        <div className="space-y-6">
            <div className="flex justify-between items-center">
                <div className="flex items-center gap-3">
                    <div className="bg-gradient-to-br from-indigo-500 to-purple-500 text-white rounded-xl p-2 shadow-lg">
                        <Briefcase size={24} />
                    </div>
                    <h3 className="text-2xl font-bold bg-gradient-to-r from-indigo-600 to-purple-600 bg-clip-text text-transparent">Internships & Training</h3>
                </div>
                <button
                    onClick={addInternship}
                    className="flex items-center gap-2 px-5 py-2.5 bg-gradient-to-r from-indigo-500 to-purple-500 text-white rounded-xl hover:from-indigo-600 hover:to-purple-600 transition-all text-sm font-semibold shadow-lg hover:shadow-xl hover:scale-105 transform"
                >
                    <Plus size={18} />
                    Add Internship
                </button>
            </div>

            <div className="space-y-6">
                {data.map((exp, index) => (
                    <div key={exp.id} className="p-6 border-2 border-indigo-200 rounded-2xl bg-gradient-to-br from-indigo-50 to-purple-50 space-y-4 shadow-lg hover:shadow-xl transition-all">
                        <div className="flex justify-between items-start">
                            <span className="text-base font-bold text-indigo-700 bg-white px-4 py-1.5 rounded-full shadow-sm">Internship #{index + 1}</span>
                            <button
                                onClick={() => removeInternship(exp.id)}
                                className="text-red-600 hover:text-red-700 bg-white p-2 rounded-xl hover:bg-red-50 transition-all shadow-sm"
                            >
                                <Trash2 size={20} />
                            </button>
                        </div>

                        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                            <div>
                                <label className="block text-sm font-bold text-gray-800 mb-2">
                                    Organization / Company *
                                </label>
                                <input
                                    type="text"
                                    value={exp.company}
                                    onChange={(e) => updateInternship(exp.id, 'company', e.target.value)}
                                    className="w-full px-4 py-3 border-2 border-indigo-200 rounded-xl focus:ring-4 focus:ring-indigo-300 focus:border-indigo-500 transition-all font-medium bg-white shadow-sm hover:shadow-md"
                                    placeholder="e.g. Google India"
                                />
                            </div>

                            <div>
                                <label className="block text-sm font-bold text-gray-800 mb-2">
                                    Role / Position *
                                </label>
                                <input
                                    type="text"
                                    value={exp.position}
                                    onChange={(e) => updateInternship(exp.id, 'position', e.target.value)}
                                    className="w-full px-4 py-3 border-2 border-purple-200 rounded-xl focus:ring-4 focus:ring-purple-300 focus:border-purple-500 transition-all font-medium bg-white shadow-sm hover:shadow-md"
                                    placeholder="e.g. Software Engineering Intern"
                                />
                            </div>

                            <div className="md:col-span-2">
                                <label className="block text-sm font-bold text-gray-800 mb-2">
                                    Location
                                </label>
                                <input
                                    type="text"
                                    value={exp.location}
                                    onChange={(e) => updateInternship(exp.id, 'location', e.target.value)}
                                    className="w-full px-4 py-3 border-2 border-cyan-200 rounded-xl focus:ring-4 focus:ring-cyan-300 focus:border-cyan-500 transition-all font-medium bg-white shadow-sm hover:shadow-md"
                                    placeholder="Remote / City"
                                />
                            </div>
                        </div>

                        <div className="flex gap-3">
                            <div className="flex-1">
                                <label className="block text-sm font-bold text-gray-800 mb-2">
                                    Start Date *
                                </label>
                                <input
                                    type="month"
                                    value={exp.startDate}
                                    onChange={(e) => updateInternship(exp.id, 'startDate', e.target.value)}
                                    className="w-full px-4 py-3 border-2 border-blue-200 rounded-xl focus:ring-4 focus:ring-blue-300 focus:border-blue-500 transition-all font-medium bg-white shadow-sm hover:shadow-md"
                                />
                            </div>

                            <div className="flex-1">
                                <label className="block text-sm font-bold text-gray-800 mb-2">
                                    End Date
                                </label>
                                <input
                                    type="month"
                                    value={exp.endDate}
                                    onChange={(e) => updateInternship(exp.id, 'endDate', e.target.value)}
                                    disabled={exp.current}
                                    className="w-full px-4 py-3 border-2 border-purple-200 rounded-xl focus:ring-4 focus:ring-purple-300 focus:border-purple-500 transition-all font-medium bg-white shadow-sm hover:shadow-md disabled:bg-gray-100"
                                />
                            </div>
                        </div>

                        <div className="flex items-center">
                            <input
                                type="checkbox"
                                checked={exp.current}
                                onChange={(e) => updateInternship(exp.id, 'current', e.target.checked)}
                                className="w-4 h-4 text-indigo-600 rounded focus:ring-indigo-500"
                            />
                            <label className="ml-2 text-sm text-gray-700">
                                I currently work here
                            </label>
                        </div>

                        <div>
                            <div className="flex justify-between items-center mb-2">
                                <label className="block text-sm font-medium text-gray-700">
                                    Responsibilities & Learning
                                </label>
                                <button
                                    onClick={() => autoGenerateDescription(exp.id, exp.position, exp.company)}
                                    disabled={generatingFor === exp.id || !exp.position}
                                    className="flex items-center gap-1.5 px-3 py-1 bg-gradient-to-r from-indigo-600 to-purple-600 text-white rounded-lg hover:from-indigo-700 hover:to-purple-700 transition-all text-xs font-medium disabled:opacity-50 disabled:cursor-not-allowed shadow-sm"
                                >
                                    {generatingFor === exp.id ? (
                                        <>
                                            <Loader2 size={14} className="animate-spin" />
                                            Generating...
                                        </>
                                    ) : (
                                        <>
                                            <Sparkles size={14} />
                                            AI Generate
                                        </>
                                    )}
                                </button>
                                {exp.description && (
                                    <button
                                        onClick={() => handleImproveDescription(exp.id, exp.description)}
                                        disabled={improvingFor === exp.id || generatingFor === exp.id}
                                        className="flex items-center gap-1.5 px-3 py-1 bg-gradient-to-r from-purple-600 to-pink-600 text-white rounded-lg hover:from-purple-700 hover:to-pink-700 transition-all text-xs font-medium disabled:opacity-50 disabled:cursor-not-allowed shadow-sm"
                                    >
                                        {improvingFor === exp.id ? (
                                            <>
                                                <Loader2 size={14} className="animate-spin" />
                                                Improving...
                                            </>
                                        ) : (
                                            <>
                                                <Sparkles size={14} />
                                                AI Improve {targetJD ? '(Targeted)' : ''}
                                            </>
                                        )}
                                    </button>
                                )}
                            </div>
                            <textarea
                                value={exp.description}
                                onChange={(e) => updateInternship(exp.id, 'description', e.target.value)}
                                rows={4}
                                className="w-full px-3 py-2.5 border border-gray-300 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 transition-all text-sm"
                                placeholder="Describe what you did and learned during this internship..."
                            />
                        </div>
                    </div>
                ))}

                {data.length === 0 && (
                    <div className="text-center py-8 text-gray-500">
                        No internships added yet.
                    </div>
                )}
            </div>
        </div>
    );
}

import { Briefcase } from 'lucide-react';
